Sync index.html to bin/weapon-url-opener

diff --git a/bin/weapon-url-opener b/bin/weapon-url-opener
--- a/bin/weapon-url-opener
+++ b/bin/weapon-url-opener
@@ -17,7 +17,7 @@
 
 # ============================================================
 # Script Name  :  wuo.sh / weapon-url-opener.sh
-# Version      : 1.5
+# Version      : 1.6
 # Description  : Switch downloader scripts easily and quickly for termux-url-opener purpose.
 # Author       : Luis Adha (luisadha.my.id)
 # Created Date : 2025-Feb-05 (Wedn)
@@ -36,8 +36,8 @@ SCRIPT_NAME=${BASH_SOURCE[0]##*/}
 BIN="${PREFIX}/bin"
 description="This tool manages local repository directories, displays the main executable of each repository, and integrates as a plugin for Termux-Url-Opener."
 version_ztme="1.4.1"
-version_wuo="1.5"
-version_both="1.4.1(1.5)"
+version_wuo="1.6"
+version_both="1.4.1(1.6)"
 banner='[ZTME-TOOLBOX]'
 inst=$(for cmd in ztme-toolbox weapon-url-opener; do which "$cmd" 2>/dev/null; done | xargs -n1 dirname | xargs | sed 's/\ /\ \&\ /g' )
 inst=${inst:-"Not Installed"}
@@ -52,12 +52,21 @@ unlock="Unlock for full experiences with"
 if [[ -e /proc/self/fd/63 && $(readlink /proc/self/fd/63) == pipe:* ]]; then
         #echo "Skrip dijalankan via source <(curl ...)"
         run_with_curl=true
-        user_agent='curl'
+        user_agent='curl'		
 fi
-if [[ ${BASH_SOURCE[0]} != "$0" && "${run_with_curl}" != "true" ]]; then
+		
+if [[ "${run_with_curl}" != "true" ]]; then
+	user_agent='pipe'
+	echo "User Agent: ${user_agent}"	
+	echo -e "\nError: Don't use \`curl -L ${SCRIPT_NAME:-$APPNAME} | bash'";
+	echo -e "Use \`bash ${SCRIPT_NAME:-$APP}' or \`${SCRIPT_NAME:-$APP}'";
+    return 127 2>/dev/null || exit 127
+fi
+		
+if [[ ${BASH_SOURCE[0]} != "$0" ]]; then
        user_agent='source'
        echo -e "User Agent: $(echo "$user_agent" | awk -F/ '{print $NF}')";
-		echo -e "\nError: Don't use \`source ${SCRIPT_NAME:-$APP}' or \`curl -L ${SCRIPT_NAME:-$APPNAME} | bash'";
+		echo -e "\nError: Don't use \`source ${SCRIPT_NAME:-$APP}' ";
 		echo -e "Use \`bash ${SCRIPT_NAME:-$APP}' or \`${SCRIPT_NAME:-$APP}'"
     return 127 2>/dev/null || exit 127
 fi
