Sync index.html to bin/weapon-url-opener

diff --git a/bin/weapon-url-opener b/bin/weapon-url-opener
--- a/bin/weapon-url-opener
+++ b/bin/weapon-url-opener
@@ -73,7 +73,12 @@ if [[ ${BASH_SOURCE[0]} != "$0" && "${run_with_curl}" != "true" ]]; then
 		echo -e "Use \`bash ${SCRIPT_NAME:-$APP}' or \`${SCRIPT_NAME:-$APP}'"
     return 127 2>/dev/null || exit 127
 fi
-
+	
+if [ ! -t 0 ]; then
+  echo "[error] This script requires an interactive terminal (tty)."
+  exit 1
+fi
+	
 mkdir -p ~/bin
 touch ~/bin/termux-url-opener 2>/dev/null;
 SELFMD5="$(md5sum ~/bin/ztme-toolbox.sh 2>/dev/null | cut -d' ' -f1)"
